# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/Buy_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Buy_Form(object):
    def setupUi(self, Buy_Form):
        Buy_Form.setObjectName("Buy_Form")
        Buy_Form.resize(908, 627)
        self.Discription = QtWidgets.QPlainTextEdit(Buy_Form)
        self.Discription.setGeometry(QtCore.QRect(570, 130, 291, 361))
        self.Discription.setObjectName("Discription")
        self.Pic = QtWidgets.QLabel(Buy_Form)
        self.Pic.setGeometry(QtCore.QRect(100, 80, 451, 421))
        self.Pic.setText("")
        self.Pic.setPixmap(QtGui.QPixmap("../uis\\local/1.png"))
        self.Pic.setObjectName("Pic")
        self.Seller_btn = QtWidgets.QPushButton(Buy_Form)
        self.Seller_btn.setGeometry(QtCore.QRect(440, 540, 201, 71))
        self.Seller_btn.setObjectName("Seller_btn")
        self.Buy_btn = QtWidgets.QPushButton(Buy_Form)
        self.Buy_btn.setGeometry(QtCore.QRect(660, 540, 201, 71))
        self.Buy_btn.setObjectName("Buy_btn")

        self.retranslateUi(Buy_Form)
        QtCore.QMetaObject.connectSlotsByName(Buy_Form)

    def retranslateUi(self, Buy_Form):
        _translate = QtCore.QCoreApplication.translate
        Buy_Form.setWindowTitle(_translate("Buy_Form", "Form"))
        self.Discription.setPlainText(_translate("Buy_Form", "产品详情"))
        self.Seller_btn.setText(_translate("Buy_Form", "问卖家"))
        self.Buy_btn.setText(_translate("Buy_Form", "购买"))
