# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/Edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit_Form(object):
    def setupUi(self, Edit_Form):
        Edit_Form.setObjectName("Edit_Form")
        Edit_Form.resize(930, 634)
        self.Product = QtWidgets.QGraphicsView(Edit_Form)
        self.Product.setGeometry(QtCore.QRect(70, 50, 471, 321))
        self.Product.setObjectName("Product")
        self.Edit_pic_btn = QtWidgets.QPushButton(Edit_Form)
        self.Edit_pic_btn.setGeometry(QtCore.QRect(180, 390, 231, 24))
        self.Edit_pic_btn.setObjectName("Edit_pic_btn")
        self.Name_input = QtWidgets.QTextEdit(Edit_Form)
        self.Name_input.setGeometry(QtCore.QRect(660, 70, 251, 31))
        self.Name_input.setObjectName("Name_input")
        self.Condition_input = QtWidgets.QTextEdit(Edit_Form)
        self.Condition_input.setGeometry(QtCore.QRect(660, 130, 251, 31))
        self.Condition_input.setObjectName("Condition_input")
        self.Discrip_input = QtWidgets.QTextEdit(Edit_Form)
        self.Discrip_input.setGeometry(QtCore.QRect(660, 200, 251, 141))
        self.Discrip_input.setObjectName("Discrip_input")
        self.label = QtWidgets.QLabel(Edit_Form)
        self.label.setGeometry(QtCore.QRect(590, 70, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Edit_Form)
        self.label_2.setGeometry(QtCore.QRect(570, 130, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Edit_Form)
        self.label_3.setGeometry(QtCore.QRect(560, 200, 91, 20))
        self.label_3.setObjectName("label_3")
        self.OK_btn = QtWidgets.QPushButton(Edit_Form)
        self.OK_btn.setGeometry(QtCore.QRect(790, 590, 89, 24))
        self.OK_btn.setObjectName("OK_btn")
        self.Cancel_btn = QtWidgets.QPushButton(Edit_Form)
        self.Cancel_btn.setGeometry(QtCore.QRect(650, 590, 89, 24))
        self.Cancel_btn.setObjectName("Cancel_btn")

        self.retranslateUi(Edit_Form)
        QtCore.QMetaObject.connectSlotsByName(Edit_Form)

    def retranslateUi(self, Edit_Form):
        _translate = QtCore.QCoreApplication.translate
        Edit_Form.setWindowTitle(_translate("Edit_Form", "Form"))
        self.Edit_pic_btn.setText(_translate("Edit_Form", "Edit picture"))
        self.label.setText(_translate("Edit_Form", "Name"))
        self.label_2.setText(_translate("Edit_Form", "Condition"))
        self.label_3.setText(_translate("Edit_Form", "Discription"))
        self.OK_btn.setText(_translate("Edit_Form", "Confrim"))
        self.Cancel_btn.setText(_translate("Edit_Form", "Cancel"))
