# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogInSignUpForm(object):
    def setupUi(self, LogInSignUpForm):
        LogInSignUpForm.setObjectName("LogInSignUpForm")
        LogInSignUpForm.resize(289, 200)
        LogInSignUpForm.setMinimumSize(QtCore.QSize(289, 200))
        LogInSignUpForm.setMaximumSize(QtCore.QSize(289, 200))
        LogInSignUpForm.setFocusPolicy(QtCore.Qt.NoFocus)
        LogInSignUpForm.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(LogInSignUpForm)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 3, 281, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login = QtWidgets.QLabel(self.layoutWidget)
        self.label_login.setMinimumSize(QtCore.QSize(0, 0))
        self.label_login.setStyleSheet("")
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.Log_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.Log_input.setObjectName("Log_input")
        self.verticalLayout.addWidget(self.Log_input)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        self.label_password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_password.setStyleSheet("")
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.Password_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.Password_input.setObjectName("Password_input")
        self.verticalLayout.addWidget(self.Password_input)
        self.Log_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Log_btn.setAutoRepeat(False)
        self.Log_btn.setObjectName("Log_btn")
        self.verticalLayout.addWidget(self.Log_btn)
        self.Sgn_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Sgn_btn.setObjectName("Sgn_btn")
        self.verticalLayout.addWidget(self.Sgn_btn)
        LogInSignUpForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogInSignUpForm)
        QtCore.QMetaObject.connectSlotsByName(LogInSignUpForm)

    def retranslateUi(self, LogInSignUpForm):
        _translate = QtCore.QCoreApplication.translate
        LogInSignUpForm.setWindowTitle(_translate("LogInSignUpForm", "Login"))
        self.label_login.setText(_translate("LogInSignUpForm", "手机号"))
        self.label_password.setText(_translate("LogInSignUpForm", "密码"))
        self.Log_btn.setText(_translate("LogInSignUpForm", "登录"))
        self.Sgn_btn.setText(_translate("LogInSignUpForm", "注册"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogInSignUpForm = QtWidgets.QMainWindow()
    ui = Ui_LogInSignUpForm()
    ui.setupUi(LogInSignUpForm)
    LogInSignUpForm.show()
    sys.exit(app.exec_())
