# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/Mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 588)
        self.pic_3 = QtWidgets.QLabel(Form)
        self.pic_3.setGeometry(QtCore.QRect(220, 316, 191, 91))
        self.pic_3.setObjectName("pic_3")
        self.name_2 = QtWidgets.QLabel(Form)
        self.name_2.setGeometry(QtCore.QRect(500, 234, 171, 21))
        self.name_2.setObjectName("name_2")
        self.pic_2 = QtWidgets.QLabel(Form)
        self.pic_2.setGeometry(QtCore.QRect(500, 130, 191, 91))
        self.pic_2.setObjectName("pic_2")
        self.pic_4 = QtWidgets.QLabel(Form)
        self.pic_4.setGeometry(QtCore.QRect(500, 316, 191, 91))
        self.pic_4.setObjectName("pic_4")
        self.info_4_btn = QtWidgets.QPushButton(Form)
        self.info_4_btn.setGeometry(QtCore.QRect(500, 446, 201, 31))
        self.info_4_btn.setObjectName("info_4_btn")
        self.name_4 = QtWidgets.QLabel(Form)
        self.name_4.setGeometry(QtCore.QRect(500, 420, 171, 21))
        self.name_4.setObjectName("name_4")
        self.prev_page_btn = QtWidgets.QPushButton(Form)
        self.prev_page_btn.setGeometry(QtCore.QRect(550, 530, 89, 24))
        self.prev_page_btn.setObjectName("prev_page_btn")
        self.info_2_btn = QtWidgets.QPushButton(Form)
        self.info_2_btn.setGeometry(QtCore.QRect(500, 260, 201, 31))
        self.info_2_btn.setObjectName("info_2_btn")
        self.Search_input = QtWidgets.QTextEdit(Form)
        self.Search_input.setGeometry(QtCore.QRect(180, 70, 481, 31))
        self.Search_input.setObjectName("Search_input")
        self.Search_btn = QtWidgets.QPushButton(Form)
        self.Search_btn.setGeometry(QtCore.QRect(670, 70, 81, 31))
        self.Search_btn.setObjectName("Search_btn")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 151, 491))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Log_Sgn_btn = QtWidgets.QPushButton(self.groupBox)
        self.Log_Sgn_btn.setGeometry(QtCore.QRect(0, 36, 149, 23))
        self.Log_Sgn_btn.setObjectName("Log_Sgn_btn")
        self.Logo_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.Logo_2.setGeometry(QtCore.QRect(0, 448, 151, 31))
        self.Logo_2.setObjectName("Logo_2")
        self.Tag2_btn = QtWidgets.QPushButton(self.groupBox)
        self.Tag2_btn.setGeometry(QtCore.QRect(0, 286, 149, 23))
        self.Tag2_btn.setObjectName("Tag2_btn")
        self.Tag1_btn = QtWidgets.QPushButton(self.groupBox)
        self.Tag1_btn.setGeometry(QtCore.QRect(0, 250, 149, 23))
        self.Tag1_btn.setObjectName("Tag1_btn")
        self.Release_prod_btn = QtWidgets.QPushButton(self.groupBox)
        self.Release_prod_btn.setGeometry(QtCore.QRect(0, 78, 149, 23))
        self.Release_prod_btn.setObjectName("Release_prod_btn")
        self.Category = QtWidgets.QTextBrowser(self.groupBox)
        self.Category.setGeometry(QtCore.QRect(0, 198, 151, 31))
        self.Category.setObjectName("Category")
        self.Prod_bought_btn = QtWidgets.QPushButton(self.groupBox)
        self.Prod_bought_btn.setGeometry(QtCore.QRect(0, 162, 149, 23))
        self.Prod_bought_btn.setObjectName("Prod_bought_btn")
        self.Tag4_btn = QtWidgets.QPushButton(self.groupBox)
        self.Tag4_btn.setGeometry(QtCore.QRect(0, 358, 149, 23))
        self.Tag4_btn.setObjectName("Tag4_btn")
        self.Prod_sold_btn = QtWidgets.QPushButton(self.groupBox)
        self.Prod_sold_btn.setGeometry(QtCore.QRect(0, 120, 149, 23))
        self.Prod_sold_btn.setObjectName("Prod_sold_btn")
        self.Tag3_btn = QtWidgets.QPushButton(self.groupBox)
        self.Tag3_btn.setGeometry(QtCore.QRect(0, 322, 149, 23))
        self.Tag3_btn.setObjectName("Tag3_btn")
        self.info_3_btn = QtWidgets.QPushButton(Form)
        self.info_3_btn.setGeometry(QtCore.QRect(220, 446, 201, 31))
        self.info_3_btn.setObjectName("info_3_btn")
        self.Logo_1 = QtWidgets.QTextBrowser(Form)
        self.Logo_1.setGeometry(QtCore.QRect(300, 10, 261, 51))
        self.Logo_1.setObjectName("Logo_1")
        self.name_1 = QtWidgets.QLabel(Form)
        self.name_1.setGeometry(QtCore.QRect(220, 234, 171, 21))
        self.name_1.setObjectName("name_1")
        self.pic_1 = QtWidgets.QLabel(Form)
        self.pic_1.setGeometry(QtCore.QRect(220, 130, 191, 91))
        self.pic_1.setObjectName("pic_1")
        self.next_page_btn = QtWidgets.QPushButton(Form)
        self.next_page_btn.setGeometry(QtCore.QRect(650, 530, 89, 24))
        self.next_page_btn.setObjectName("next_page_btn")
        self.info_1_btn = QtWidgets.QPushButton(Form)
        self.info_1_btn.setGeometry(QtCore.QRect(220, 260, 201, 31))
        self.info_1_btn.setObjectName("info_1_btn")
        self.name_3 = QtWidgets.QLabel(Form)
        self.name_3.setGeometry(QtCore.QRect(220, 420, 171, 21))
        self.name_3.setObjectName("name_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pic_3.setText(_translate("Form", "picture"))
        self.name_2.setText(_translate("Form", "name"))
        self.pic_2.setText(_translate("Form", "picture"))
        self.pic_4.setText(_translate("Form", "picture"))
        self.info_4_btn.setText(_translate("Form", "see info"))
        self.name_4.setText(_translate("Form", "name"))
        self.prev_page_btn.setText(_translate("Form", "prev"))
        self.info_2_btn.setText(_translate("Form", "see info"))
        self.Search_btn.setText(_translate("Form", "Search"))
        self.Log_Sgn_btn.setText(_translate("Form", "Login/Sign"))
        self.Logo_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">咸鱼二手</span></p></body></html>"))
        self.Tag2_btn.setText(_translate("Form", "Tag"))
        self.Tag1_btn.setText(_translate("Form", "Tag"))
        self.Release_prod_btn.setText(_translate("Form", "Release Product"))
        self.Category.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Categories</span></p></body></html>"))
        self.Prod_bought_btn.setText(_translate("Form", "Products bought"))
        self.Tag4_btn.setText(_translate("Form", "Tag"))
        self.Prod_sold_btn.setText(_translate("Form", "Products sold"))
        self.Tag3_btn.setText(_translate("Form", "Tag"))
        self.info_3_btn.setText(_translate("Form", "see info"))
        self.Logo_1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">咸鱼二手</span></p></body></html>"))
        self.name_1.setText(_translate("Form", "name"))
        self.pic_1.setText(_translate("Form", "picture"))
        self.next_page_btn.setText(_translate("Form", "next"))
        self.info_1_btn.setText(_translate("Form", "see info"))
        self.name_3.setText(_translate("Form", "name"))
