# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/ManageProducts.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageProducts_Form(object):
    def setupUi(self, ManageProducts_Form):
        ManageProducts_Form.setObjectName("ManageProducts_Form")
        ManageProducts_Form.resize(751, 494)
        self.Edit_1_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.Edit_1_btn.setGeometry(QtCore.QRect(90, 160, 41, 20))
        self.Edit_1_btn.setObjectName("Edit_1_btn")
        self.pro1_view = QtWidgets.QGraphicsView(ManageProducts_Form)
        self.pro1_view.setGeometry(QtCore.QRect(50, 50, 201, 101))
        self.pro1_view.setObjectName("pro1_view")
        self.delete_1_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.delete_1_btn.setGeometry(QtCore.QRect(140, 160, 111, 20))
        self.delete_1_btn.setObjectName("delete_1_btn")
        self.pro2_view = QtWidgets.QGraphicsView(ManageProducts_Form)
        self.pro2_view.setGeometry(QtCore.QRect(50, 200, 201, 101))
        self.pro2_view.setObjectName("pro2_view")
        self.delete_3_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.delete_3_btn.setGeometry(QtCore.QRect(140, 310, 111, 20))
        self.delete_3_btn.setObjectName("delete_3_btn")
        self.Edit_3_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.Edit_3_btn.setGeometry(QtCore.QRect(90, 310, 41, 20))
        self.Edit_3_btn.setObjectName("Edit_3_btn")
        self.pro3_view = QtWidgets.QGraphicsView(ManageProducts_Form)
        self.pro3_view.setGeometry(QtCore.QRect(300, 50, 201, 101))
        self.pro3_view.setObjectName("pro3_view")
        self.delete_2_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.delete_2_btn.setGeometry(QtCore.QRect(390, 160, 111, 20))
        self.delete_2_btn.setObjectName("delete_2_btn")
        self.Edit_2_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.Edit_2_btn.setGeometry(QtCore.QRect(340, 160, 41, 20))
        self.Edit_2_btn.setObjectName("Edit_2_btn")
        self.pro4_view = QtWidgets.QGraphicsView(ManageProducts_Form)
        self.pro4_view.setGeometry(QtCore.QRect(300, 200, 201, 101))
        self.pro4_view.setObjectName("pro4_view")
        self.delete_4_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.delete_4_btn.setGeometry(QtCore.QRect(390, 310, 111, 20))
        self.delete_4_btn.setObjectName("delete_4_btn")
        self.Edit_4_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.Edit_4_btn.setGeometry(QtCore.QRect(340, 310, 41, 20))
        self.Edit_4_btn.setObjectName("Edit_4_btn")
        self.Prev_page_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.Prev_page_btn.setGeometry(QtCore.QRect(470, 440, 96, 24))
        self.Prev_page_btn.setObjectName("Prev_page_btn")
        self.Next_page_btn = QtWidgets.QPushButton(ManageProducts_Form)
        self.Next_page_btn.setGeometry(QtCore.QRect(618, 440, 91, 24))
        self.Next_page_btn.setObjectName("Next_page_btn")

        self.retranslateUi(ManageProducts_Form)
        QtCore.QMetaObject.connectSlotsByName(ManageProducts_Form)

    def retranslateUi(self, ManageProducts_Form):
        _translate = QtCore.QCoreApplication.translate
        ManageProducts_Form.setWindowTitle(_translate("ManageProducts_Form", "Form"))
        self.Edit_1_btn.setText(_translate("ManageProducts_Form", "Edit"))
        self.delete_1_btn.setText(_translate("ManageProducts_Form", "Off the shelf"))
        self.delete_3_btn.setText(_translate("ManageProducts_Form", "Off the shelf"))
        self.Edit_3_btn.setText(_translate("ManageProducts_Form", "Edit"))
        self.delete_2_btn.setText(_translate("ManageProducts_Form", "Off the shelf"))
        self.Edit_2_btn.setText(_translate("ManageProducts_Form", "Edit"))
        self.delete_4_btn.setText(_translate("ManageProducts_Form", "Off the shelf"))
        self.Edit_4_btn.setText(_translate("ManageProducts_Form", "Edit"))
        self.Prev_page_btn.setText(_translate("ManageProducts_Form", "Prev"))
        self.Next_page_btn.setText(_translate("ManageProducts_Form", "Next"))
