# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/Sell_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sell_Form(object):
    def setupUi(self, Sell_Form):
        Sell_Form.setObjectName("Sell_Form")
        Sell_Form.resize(789, 563)
        self.Upload_pic = QtWidgets.QComboBox(Sell_Form)
        self.Upload_pic.setGeometry(QtCore.QRect(30, 360, 89, 23))
        self.Upload_pic.setObjectName("Upload_pic")
        self.label_2 = QtWidgets.QLabel(Sell_Form)
        self.label_2.setGeometry(QtCore.QRect(30, 330, 111, 31))
        self.label_2.setObjectName("label_2")
        self.Browse_btn = QtWidgets.QToolButton(Sell_Form)
        self.Browse_btn.setGeometry(QtCore.QRect(120, 360, 48, 22))
        self.Browse_btn.setObjectName("Browse_btn")
        self.Discrip_input = QtWidgets.QTextEdit(Sell_Form)
        self.Discrip_input.setGeometry(QtCore.QRect(30, 60, 571, 161))
        self.Discrip_input.setObjectName("Discrip_input")
        self.Tag_select = QtWidgets.QComboBox(Sell_Form)
        self.Tag_select.setGeometry(QtCore.QRect(30, 280, 89, 23))
        self.Tag_select.setObjectName("Tag_select")
        self.label_1 = QtWidgets.QLabel(Sell_Form)
        self.label_1.setGeometry(QtCore.QRect(30, 240, 111, 31))
        self.label_1.setObjectName("label_1")
        self.Release_btn = QtWidgets.QPushButton(Sell_Form)
        self.Release_btn.setGeometry(QtCore.QRect(610, 500, 151, 51))
        self.Release_btn.setObjectName("Release_btn")
        self.Title = QtWidgets.QLabel(Sell_Form)
        self.Title.setGeometry(QtCore.QRect(30, 10, 71, 31))
        self.Title.setObjectName("Title")

        self.retranslateUi(Sell_Form)
        QtCore.QMetaObject.connectSlotsByName(Sell_Form)

    def retranslateUi(self, Sell_Form):
        _translate = QtCore.QCoreApplication.translate
        Sell_Form.setWindowTitle(_translate("Sell_Form", "Form"))
        self.label_2.setText(_translate("Sell_Form", "上传图片"))
        self.Browse_btn.setText(_translate("Sell_Form", "..."))
        self.Discrip_input.setHtml(_translate("Sell_Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入商品介绍</p></body></html>"))
        self.label_1.setText(_translate("Sell_Form", "选择商品标签"))
        self.Release_btn.setText(_translate("Sell_Form", "发布"))
        self.Title.setText(_translate("Sell_Form", "发布商品"))
