# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/Buy_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Buy_Form(object):
    def setupUi(self, Buy_Form):
        Buy_Form.setObjectName("Buy_Form")
        Buy_Form.resize(901, 573)
        self.Discription = QtWidgets.QTextBrowser(Buy_Form)
        self.Discription.setGeometry(QtCore.QRect(560, 120, 301, 181))
        self.Discription.setObjectName("Discription")
        self.Pic = QtWidgets.QLabel(Buy_Form)
        self.Pic.setGeometry(QtCore.QRect(40, 50, 481, 311))
        self.Pic.setText("")
        self.Pic.setPixmap(QtGui.QPixmap("uis\\local/1.png"))
        self.Pic.setScaledContents(True)
        self.Pic.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Pic.setObjectName("Pic")
        self.Back_btn = QtWidgets.QPushButton(Buy_Form)
        self.Back_btn.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.Back_btn.setObjectName("Back_btn")
        self.Comment = QtWidgets.QTextBrowser(Buy_Form)
        self.Comment.setGeometry(QtCore.QRect(560, 330, 301, 81))
        self.Comment.setObjectName("Comment")
        self.next_page_btn = QtWidgets.QPushButton(Buy_Form)
        self.next_page_btn.setGeometry(QtCore.QRect(770, 420, 89, 24))
        self.next_page_btn.setObjectName("next_page_btn")
        self.prev_page_btn = QtWidgets.QPushButton(Buy_Form)
        self.prev_page_btn.setGeometry(QtCore.QRect(670, 420, 89, 24))
        self.prev_page_btn.setObjectName("prev_page_btn")
        self.label = QtWidgets.QLabel(Buy_Form)
        self.label.setGeometry(QtCore.QRect(570, 80, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Buy_Form)
        self.label_2.setGeometry(QtCore.QRect(720, 80, 31, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Buy_Form)
        self.label_3.setGeometry(QtCore.QRect(570, 40, 31, 21))
        self.label_3.setObjectName("label_3")
        self.name_label = QtWidgets.QLabel(Buy_Form)
        self.name_label.setGeometry(QtCore.QRect(611, 40, 251, 21))
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.price_label = QtWidgets.QLabel(Buy_Form)
        self.price_label.setGeometry(QtCore.QRect(610, 80, 81, 21))
        self.price_label.setText("")
        self.price_label.setObjectName("price_label")
        self.stock_label = QtWidgets.QLabel(Buy_Form)
        self.stock_label.setGeometry(QtCore.QRect(770, 80, 81, 21))
        self.stock_label.setText("")
        self.stock_label.setObjectName("stock_label")

        self.retranslateUi(Buy_Form)
        QtCore.QMetaObject.connectSlotsByName(Buy_Form)

    def retranslateUi(self, Buy_Form):
        _translate = QtCore.QCoreApplication.translate
        Buy_Form.setWindowTitle(_translate("Buy_Form", "Form"))
        self.Discription.setHtml(_translate("Buy_Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">产品详情</p></body></html>"))
        self.Back_btn.setText(_translate("Buy_Form", "返回主页"))
        self.Comment.setHtml(_translate("Buy_Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">用户评价</p></body></html>"))
        self.next_page_btn.setText(_translate("Buy_Form", "下一条"))
        self.prev_page_btn.setText(_translate("Buy_Form", "上一条"))
        self.label.setText(_translate("Buy_Form", "价格"))
        self.label_2.setText(_translate("Buy_Form", "库存"))
        self.label_3.setText(_translate("Buy_Form", "名称"))
