# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/Chatlog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 566)
        self.next = QtWidgets.QPushButton(Dialog)
        self.next.setGeometry(QtCore.QRect(300, 310, 80, 20))
        self.next.setObjectName("next")
        self.typein = QtWidgets.QTextEdit(Dialog)
        self.typein.setGeometry(QtCore.QRect(20, 450, 281, 91))
        self.typein.setObjectName("typein")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 80, 271, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.text1.setObjectName("text1")
        self.verticalLayout.addWidget(self.text1)
        self.text2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.text2.setObjectName("text2")
        self.verticalLayout.addWidget(self.text2)
        self.text3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.text3.setObjectName("text3")
        self.verticalLayout.addWidget(self.text3)
        self.text4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.text4.setObjectName("text4")
        self.verticalLayout.addWidget(self.text4)
        self.text5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.text5.setObjectName("text5")
        self.verticalLayout.addWidget(self.text5)
        self.talk_partner = QtWidgets.QLabel(Dialog)
        self.talk_partner.setGeometry(QtCore.QRect(20, 50, 171, 21))
        self.talk_partner.setObjectName("talk_partner")
        self.send = QtWidgets.QPushButton(Dialog)
        self.send.setGeometry(QtCore.QRect(310, 520, 80, 20))
        self.send.setObjectName("send")
        self.prev = QtWidgets.QPushButton(Dialog)
        self.prev.setGeometry(QtCore.QRect(300, 210, 80, 20))
        self.prev.setObjectName("prev")
        self.back = QtWidgets.QPushButton(Dialog)
        self.back.setGeometry(QtCore.QRect(20, 20, 80, 20))
        self.back.setObjectName("back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.next.setText(_translate("Dialog", "下一页"))
        self.text1.setText(_translate("Dialog", "text"))
        self.text2.setText(_translate("Dialog", "TextLabel"))
        self.text3.setText(_translate("Dialog", "TextLabel"))
        self.text4.setText(_translate("Dialog", "TextLabel"))
        self.text5.setText(_translate("Dialog", "TextLabel"))
        self.talk_partner.setText(_translate("Dialog", "who are you talking with:"))
        self.send.setText(_translate("Dialog", "发送"))
        self.prev.setText(_translate("Dialog", "上一页"))
        self.back.setText(_translate("Dialog", "返回"))
