# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/Edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sell_Form(object):
    def setupUi(self, Sell_Form):
        Sell_Form.setObjectName("Sell_Form")
        Sell_Form.resize(895, 624)
        self.label_2 = QtWidgets.QLabel(Sell_Form)
        self.label_2.setGeometry(QtCore.QRect(110, 310, 111, 31))
        self.label_2.setObjectName("label_2")
        self.Tag_select = QtWidgets.QComboBox(Sell_Form)
        self.Tag_select.setGeometry(QtCore.QRect(110, 280, 89, 23))
        self.Tag_select.setObjectName("Tag_select")
        self.label_1 = QtWidgets.QLabel(Sell_Form)
        self.label_1.setGeometry(QtCore.QRect(110, 250, 111, 31))
        self.label_1.setObjectName("label_1")
        self.Release_btn = QtWidgets.QPushButton(Sell_Form)
        self.Release_btn.setGeometry(QtCore.QRect(690, 540, 151, 51))
        self.Release_btn.setObjectName("Release_btn")
        self.Title = QtWidgets.QLabel(Sell_Form)
        self.Title.setGeometry(QtCore.QRect(110, 20, 71, 31))
        self.Title.setObjectName("Title")
        self.Back_btn = QtWidgets.QPushButton(Sell_Form)
        self.Back_btn.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.Back_btn.setObjectName("Back_btn")
        self.Openfile_btn = QtWidgets.QPushButton(Sell_Form)
        self.Openfile_btn.setGeometry(QtCore.QRect(110, 340, 89, 24))
        self.Openfile_btn.setObjectName("Openfile_btn")
        self.PathlineEdit = QtWidgets.QLineEdit(Sell_Form)
        self.PathlineEdit.setGeometry(QtCore.QRect(210, 340, 541, 23))
        self.PathlineEdit.setReadOnly(True)
        self.PathlineEdit.setObjectName("PathlineEdit")
        self.Picture = QtWidgets.QLabel(Sell_Form)
        self.Picture.setGeometry(QtCore.QRect(120, 380, 221, 181))
        self.Picture.setText("")
        self.Picture.setScaledContents(True)
        self.Picture.setObjectName("Picture")
        self.price_input = QtWidgets.QLineEdit(Sell_Form)
        self.price_input.setGeometry(QtCore.QRect(260, 280, 113, 23))
        self.price_input.setObjectName("price_input")
        self.label_3 = QtWidgets.QLabel(Sell_Form)
        self.label_3.setGeometry(QtCore.QRect(260, 250, 231, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Sell_Form)
        self.label_4.setGeometry(QtCore.QRect(420, 250, 231, 31))
        self.label_4.setObjectName("label_4")
        self.stock_input = QtWidgets.QLineEdit(Sell_Form)
        self.stock_input.setGeometry(QtCore.QRect(420, 280, 113, 23))
        self.stock_input.setObjectName("stock_input")
        self.label_5 = QtWidgets.QLabel(Sell_Form)
        self.label_5.setGeometry(QtCore.QRect(110, 50, 51, 31))
        self.label_5.setObjectName("label_5")
        self.name_input = QtWidgets.QLineEdit(Sell_Form)
        self.name_input.setGeometry(QtCore.QRect(170, 55, 581, 23))
        self.name_input.setObjectName("name_input")
        self.label_6 = QtWidgets.QLabel(Sell_Form)
        self.label_6.setGeometry(QtCore.QRect(110, 80, 61, 31))
        self.label_6.setObjectName("label_6")
        self.info_input = QtWidgets.QPlainTextEdit(Sell_Form)
        self.info_input.setGeometry(QtCore.QRect(110, 110, 641, 141))
        self.info_input.setPlainText("")
        self.info_input.setObjectName("info_input")

        self.retranslateUi(Sell_Form)
        QtCore.QMetaObject.connectSlotsByName(Sell_Form)

    def retranslateUi(self, Sell_Form):
        _translate = QtCore.QCoreApplication.translate
        Sell_Form.setWindowTitle(_translate("Sell_Form", "Form"))
        self.label_2.setText(_translate("Sell_Form", "上传图片"))
        self.label_1.setText(_translate("Sell_Form", "选择商品标签"))
        self.Release_btn.setText(_translate("Sell_Form", "发布"))
        self.Title.setText(_translate("Sell_Form", "修改商品"))
        self.Back_btn.setText(_translate("Sell_Form", "返回主页"))
        self.Openfile_btn.setText(_translate("Sell_Form", "选择图片"))
        self.label_3.setText(_translate("Sell_Form", "输入商品价格（元）"))
        self.label_4.setText(_translate("Sell_Form", "输入商品数量（件）"))
        self.label_5.setText(_translate("Sell_Form", "商品名"))
        self.label_6.setText(_translate("Sell_Form", "商品介绍"))
