# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/Recharge.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(820, 644)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        widget.setFont(font)
        widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(280, 210, 221, 191))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(widget)
        self.textEdit.setGeometry(QtCore.QRect(360, 160, 161, 21))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(260, 160, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(250, 100, 31, 16))
        self.label_2.setObjectName("label_2")
        self.bag = QtWidgets.QLCDNumber(widget)
        self.bag.setGeometry(QtCore.QRect(300, 100, 64, 23))
        self.bag.setObjectName("bag")
        self.Cancel_btn = QtWidgets.QPushButton(widget)
        self.Cancel_btn.setGeometry(QtCore.QRect(670, 600, 89, 24))
        self.Cancel_btn.setObjectName("Cancel_btn")
        self.Back_btn = QtWidgets.QPushButton(widget)
        self.Back_btn.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.Back_btn.setObjectName("Back_btn")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "充值界面"))
        self.pushButton.setText(_translate("widget", "充值!"))
        self.textEdit.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">eg 100</span></p></body></html>"))
        self.label.setText(_translate("widget", "请输入充值数目："))
        self.label_2.setText(_translate("widget", "余额："))
        self.Cancel_btn.setText(_translate("widget", "取消"))
        self.Back_btn.setText(_translate("widget", "返回主页"))
