# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/sign_up_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(370, 260)
        RegisterForm.setMinimumSize(QtCore.QSize(370, 260))
        RegisterForm.setMaximumSize(QtCore.QSize(370, 260))
        RegisterForm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(RegisterForm)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 4, 361, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.password_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 11, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.name_input.setObjectName("name_input")
        self.gridLayout.addWidget(self.name_input, 2, 0, 1, 1)
        self.label_uname = QtWidgets.QLabel(self.layoutWidget)
        self.label_uname.setMinimumSize(QtCore.QSize(0, 0))
        self.label_uname.setStyleSheet("")
        self.label_uname.setObjectName("label_uname")
        self.gridLayout.addWidget(self.label_uname, 0, 1, 1, 1)
        self.email_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.email_input.setObjectName("email_input")
        self.gridLayout.addWidget(self.email_input, 6, 1, 1, 1)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        self.label_password.setMinimumSize(QtCore.QSize(0, 0))
        self.label_password.setStyleSheet("")
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 10, 0, 1, 1)
        self.uname_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.uname_input.setObjectName("uname_input")
        self.gridLayout.addWidget(self.uname_input, 2, 1, 1, 1)
        self.reg_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.reg_btn.setObjectName("reg_btn")
        self.gridLayout.addWidget(self.reg_btn, 13, 1, 1, 1)
        self.back_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.back_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.back_btn.setObjectName("back_btn")
        self.gridLayout.addWidget(self.back_btn, 13, 0, 1, 1)
        self.label_phone = QtWidgets.QLabel(self.layoutWidget)
        self.label_phone.setMinimumSize(QtCore.QSize(0, 0))
        self.label_phone.setStyleSheet("")
        self.label_phone.setObjectName("label_phone")
        self.gridLayout.addWidget(self.label_phone, 4, 0, 1, 1)
        self.phone_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.phone_input.setObjectName("phone_input")
        self.gridLayout.addWidget(self.phone_input, 6, 0, 1, 1)
        self.label_password_rpt = QtWidgets.QLabel(self.layoutWidget)
        self.label_password_rpt.setMinimumSize(QtCore.QSize(0, 0))
        self.label_password_rpt.setStyleSheet("")
        self.label_password_rpt.setObjectName("label_password_rpt")
        self.gridLayout.addWidget(self.label_password_rpt, 10, 1, 1, 1)
        self.label_email = QtWidgets.QLabel(self.layoutWidget)
        self.label_email.setMinimumSize(QtCore.QSize(0, 0))
        self.label_email.setStyleSheet("")
        self.label_email.setObjectName("label_email")
        self.gridLayout.addWidget(self.label_email, 4, 1, 1, 1)
        self.password_rpt_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_rpt_input.setObjectName("password_rpt_input")
        self.gridLayout.addWidget(self.password_rpt_input, 11, 1, 1, 1)
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_name.setMinimumSize(QtCore.QSize(0, 0))
        self.label_name.setStyleSheet("")
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        RegisterForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "Sign up"))
        self.label_uname.setText(_translate("RegisterForm", "用户名"))
        self.label_password.setText(_translate("RegisterForm", "密码"))
        self.reg_btn.setText(_translate("RegisterForm", "注册"))
        self.back_btn.setText(_translate("RegisterForm", "返回"))
        self.label_phone.setText(_translate("RegisterForm", "手机号"))
        self.label_password_rpt.setText(_translate("RegisterForm", "确认密码"))
        self.label_email.setText(_translate("RegisterForm", "邮箱"))
        self.label_name.setText(_translate("RegisterForm", "姓名"))
