# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/View.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_View_Form(object):
    def setupUi(self, View_Form):
        View_Form.setObjectName("View_Form")
        View_Form.resize(951, 640)
        self.back_to_bought_btn = QtWidgets.QPushButton(View_Form)
        self.back_to_bought_btn.setGeometry(QtCore.QRect(790, 590, 89, 24))
        self.back_to_bought_btn.setObjectName("back_to_bought_btn")
        self.label_2 = QtWidgets.QLabel(View_Form)
        self.label_2.setGeometry(QtCore.QRect(590, 130, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(View_Form)
        self.label_3.setGeometry(QtCore.QRect(580, 200, 61, 20))
        self.label_3.setObjectName("label_3")
        self.Back_btn = QtWidgets.QPushButton(View_Form)
        self.Back_btn.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.Back_btn.setObjectName("Back_btn")
        self.Product = QtWidgets.QGraphicsView(View_Form)
        self.Product.setGeometry(QtCore.QRect(70, 50, 471, 321))
        self.Product.setObjectName("Product")
        self.label = QtWidgets.QLabel(View_Form)
        self.label.setGeometry(QtCore.QRect(590, 70, 31, 16))
        self.label.setObjectName("label")
        self.name_browser = QtWidgets.QTextBrowser(View_Form)
        self.name_browser.setGeometry(QtCore.QRect(650, 60, 191, 41))
        self.name_browser.setObjectName("name_browser")
        self.condition_browser = QtWidgets.QTextBrowser(View_Form)
        self.condition_browser.setGeometry(QtCore.QRect(650, 120, 191, 41))
        self.condition_browser.setObjectName("condition_browser")
        self.description_browser = QtWidgets.QTextBrowser(View_Form)
        self.description_browser.setGeometry(QtCore.QRect(650, 200, 261, 191))
        self.description_browser.setObjectName("description_browser")

        self.retranslateUi(View_Form)
        QtCore.QMetaObject.connectSlotsByName(View_Form)

    def retranslateUi(self, View_Form):
        _translate = QtCore.QCoreApplication.translate
        View_Form.setWindowTitle(_translate("View_Form", "Form"))
        self.back_to_bought_btn.setText(_translate("View_Form", "返回"))
        self.label_2.setText(_translate("View_Form", "条件"))
        self.label_3.setText(_translate("View_Form", "商品描述"))
        self.Back_btn.setText(_translate("View_Form", "返回主页"))
        self.label.setText(_translate("View_Form", "名称"))
